Repository nerdchanii/Algorithm_study, pull requests merged in 2021-09, with the labels that each got.

#5 ps: 너드챠니 1주차 문제 풀이
  code/nerdchanii/binarysearch/binarysearch1.py
  code/nerdchanii/hash/hash1.py
Labels: PS

#10 ps: 나무 만들기(백준)
  code/sungtae/binarysearch/finding_tree.py
Labels: PS

#12 docs: 스택
  스택과큐/stack.md
Labels: Docs

#20 docs:오탈자 수정
  스택과큐/stack.md
Labels: Docs, Modify

#11 백준/괄호 9012번
  code/sungtae/stack/백준 9012번 VPS.py
Labels: PS

#13 ps : 괄호(백준)
  code/jina/Stack/괄호(백준).py
  code/jina/Stack/탑(백준).py
Labels: PS

#15 ps: 백준9012_괄호
  code/승환/스택/baekjoon2493_top.py
  code/승환/스택/baekjoon9012_bracket.py
Labels: PS

#16 스택(괄호)
  code/junho/stack1.py
Labels: PS

#21 docs: 컨트리뷰터(스터디원) 추가
  README.md
Labels: Docs

#17 PS: 백준 Stack 문제풀이
  code/vg-rlo/stack/baekjoon_2493.py
  code/vg-rlo/stack/baekjoon_9012.py
Labels: PS

#23 ps : queue (programmers)
  code/jina/queue/다리를 지나는 트럭.py
  code/jina/queue/프린터.py
Labels: PS
